package com.painkiller.domain.github

import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

class RepoTreeOrchestratorTest {

    private val owner = "octocat"
    private val repo = "hello-world"
    private val branch = "main"

    private fun moveChange(from: String = "old/file.kt", to: String = "new/file.kt") =
        PendingChange(type = PendingChangeType.MOVE, sourcePath = from, targetPath = to)

    private fun deleteChange(path: String = "old/file.kt") =
        PendingChange(type = PendingChangeType.DELETE, sourcePath = path, targetPath = null)

    private fun uploadChange(path: String = "uploads/data.bin", blobSha: String = "upload-sha") =
        PendingChange(type = PendingChangeType.UPLOAD, sourcePath = null, targetPath = path, blobSha = blobSha)

    private fun createFolderChange(path: String = "new-folder") =
        PendingChange(type = PendingChangeType.CREATE_FOLDER, sourcePath = null, targetPath = path)

    // ─── success path ─────────────────────────────────────────────────────────

    @Test
    fun success_allApiCallsInCorrectOrder() = runTest {
        val api = TreeFakeApi()
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(moveChange()),
        )

        assertTrue("expected Success but got $result", result is RepoTreeResult.Success)
        assertEquals(
            listOf("getRef", "getCommit", "getTree", "createTree", "createCommit", "updateRef"),
            api.calls,
        )
    }

    @Test
    fun success_returnsCommitShaAndUrl() = runTest {
        val api = TreeFakeApi()
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertTrue(result is RepoTreeResult.Success)
        result as RepoTreeResult.Success
        assertEquals("commit-sha-999", result.commitSha)
        assertEquals("https://github.com/octocat/hello-world/commit/commit-sha-999", result.commitUrl)
    }

    @Test
    fun success_updateRef_usesForceIsFalse() = runTest {
        val api = TreeFakeApi()
        val orchestrator = RepoTreeOrchestrator(api)

        orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertEquals(false, api.lastUpdateRefRequest?.force)
        assertEquals("base-ref-sha", api.lastUpdateRefExpectedSha)
        assertEquals("refs/heads/main", api.lastUpdateRefRef)
    }

    @Test
    fun success_getTree_usesRecursiveTrue() = runTest {
        val api = TreeFakeApi()
        val orchestrator = RepoTreeOrchestrator(api)

        orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertTrue(api.lastGetTreeRecursive)
    }

    @Test
    fun success_upload_withNewContentBase64_createsBlobFirst() = runTest {
        val api = TreeFakeApi()
        val orchestrator = RepoTreeOrchestrator(api)

        val changes = listOf(
            PendingChange(
                type = PendingChangeType.UPLOAD,
                sourcePath = null,
                targetPath = "data/file.txt",
                newContentBase64 = "aGVsbG8gd29ybGQ=",
            )
        )

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = changes,
        )

        assertTrue("expected Success but got $result", result is RepoTreeResult.Success)
        assertEquals(
            listOf("getRef", "getCommit", "getTree", "createBlob", "createTree", "createCommit", "updateRef"),
            api.calls,
        )
        // The blob request should use base64 encoding
        assertEquals(1, api.blobRequests.size)
        assertEquals("aGVsbG8gd29ybGQ=", api.blobRequests[0].content)
        assertEquals("base64", api.blobRequests[0].encoding)
        // Tree entry should have the blob SHA, not inline content
        val treeReq = api.lastCreateTreeRequest
        assertNotNull(treeReq)
        assertEquals("blob-sha-1", treeReq!!.tree[0].sha)
    }

    @Test
    fun success_autoGeneratedCommitMessage_containsChangeSummary() = runTest {
        val api = TreeFakeApi()
        val orchestrator = RepoTreeOrchestrator(api)

        val changes = listOf(
            moveChange("old/a.kt", "new/a.kt"),
            moveChange("old/b.kt", "new/b.kt"),
            moveChange("old/c.kt", "new/c.kt"),
            createFolderChange("empty-dir"),
        )

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = changes,
        )

        assertTrue(result is RepoTreeResult.Success)
        result as RepoTreeResult.Success
        assertTrue(result.summary.contains("3 Dateien verschoben"))
        assertTrue(result.summary.contains("1 Ordner erstellt"))
    }

    @Test
    fun success_singleMove_commitMessage_usesSingular() = runTest {
        val api = TreeFakeApi()
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(moveChange()),
        )

        assertTrue(result is RepoTreeResult.Success)
        result as RepoTreeResult.Success
        assertTrue(result.summary.contains("1 Datei verschoben"))
    }

    // ─── validation ───────────────────────────────────────────────────────────

    @Test
    fun emptyChanges_returnsInvalidInput_noApiCalls() = runTest {
        val api = TreeFakeApi()
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = emptyList(),
        )

        assertTrue(result is RepoTreeResult.InvalidInput)
        assertEquals(emptyList<String>(), api.calls)
    }

    // ─── error mapping ────────────────────────────────────────────────────────

    @Test
    fun authError_atGetRef_isMapped() = runTest {
        val api = TreeFakeApi(getRefThrows = GithubGitDataException.AuthRequired())
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertTrue(result is RepoTreeResult.AuthError)
        assertEquals(listOf("getRef"), api.calls)
    }

    @Test
    fun permissionDenied_atCreateTree_isMapped() = runTest {
        val api = TreeFakeApi(createTreeThrows = GithubGitDataException.PermissionDenied())
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertTrue(result is RepoTreeResult.PermissionError)
    }

    @Test
    fun shaMismatch_atUpdateRef_isMapped() = runTest {
        val api = TreeFakeApi(updateRefThrows = GithubGitDataException.ShaMismatch())
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertTrue(result is RepoTreeResult.ShaMismatch)
        assertTrue("updateRef" in api.calls)
    }

    @Test
    fun networkError_atGetRef_isMapped() = runTest {
        val api = TreeFakeApi(getRefThrows = GithubGitDataException.NetworkUnavailable())
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertTrue(result is RepoTreeResult.NetworkError)
    }

    @Test
    fun protectedBranch_atUpdateRef_isMapped() = runTest {
        val api = TreeFakeApi(updateRefThrows = GithubGitDataException.ProtectedBranch())
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertTrue(result is RepoTreeResult.ProtectedBranch)
    }

    @Test
    fun branchNotFound_atGetRef_isMapped() = runTest {
        val api = TreeFakeApi(getRefThrows = GithubGitDataException.RefNotFound())
        val orchestrator = RepoTreeOrchestrator(api)

        val result = orchestrator.execute(
            owner = owner,
            repo = repo,
            branch = branch,
            changes = listOf(deleteChange()),
        )

        assertTrue(result is RepoTreeResult.BranchNotFound)
    }
}

/**
 * Recording fake of [GithubGitDataApi] for RepoTreeOrchestrator tests.
 *
 * Returns a tree with known entries so that MOVE/RENAME operations can
 * resolve source blob SHAs. [calls] tracks method invocations in order.
 */
private class TreeFakeApi(
    private val getRefThrows: GithubGitDataException? = null,
    private val getCommitThrows: GithubGitDataException? = null,
    private val getTreeThrows: GithubGitDataException? = null,
    private val createBlobThrows: GithubGitDataException? = null,
    private val createTreeThrows: GithubGitDataException? = null,
    private val createCommitThrows: GithubGitDataException? = null,
    private val updateRefThrows: GithubGitDataException? = null,
) : GithubGitDataApi {

    val calls: MutableList<String> = mutableListOf()
    val blobRequests: MutableList<CreateBlobRequest> = mutableListOf()

    var lastCreateTreeRequest: CreateTreeRequest? = null
        private set
    var lastUpdateRefExpectedSha: String? = null
        private set
    var lastUpdateRefRequest: UpdateRefRequest? = null
        private set
    var lastUpdateRefRef: String? = null
        private set
    var lastGetTreeRecursive: Boolean = false
        private set

    private var blobCount = 0

    private val fakeTree = listOf(
        TreeEntry(path = "old/file.kt", mode = TreeEntry.MODE_FILE, type = TreeEntry.TYPE_BLOB, sha = "source-blob-sha"),
        TreeEntry(path = "old/a.kt", mode = TreeEntry.MODE_FILE, type = TreeEntry.TYPE_BLOB, sha = "blob-a"),
        TreeEntry(path = "old/b.kt", mode = TreeEntry.MODE_FILE, type = TreeEntry.TYPE_BLOB, sha = "blob-b"),
        TreeEntry(path = "old/c.kt", mode = TreeEntry.MODE_FILE, type = TreeEntry.TYPE_BLOB, sha = "blob-c"),
        TreeEntry(path = "docs/readme.md", mode = TreeEntry.MODE_FILE, type = TreeEntry.TYPE_BLOB, sha = "docs-sha"),
    )

    override suspend fun getRef(owner: String, repo: String, ref: String): GitRef {
        calls += "getRef"
        getRefThrows?.let { throw it }
        return GitRef(
            ref = "refs/$ref",
            obj = GitRefObject(sha = "base-ref-sha", type = "commit"),
        )
    }

    override suspend fun getCommit(owner: String, repo: String, commitSha: String): GitCommit {
        calls += "getCommit"
        getCommitThrows?.let { throw it }
        return GitCommit(
            sha = commitSha,
            message = "base commit",
            tree = GitTreeRef(sha = "base-tree-sha"),
        )
    }

    override suspend fun getTree(
        owner: String,
        repo: String,
        treeSha: String,
        recursive: Boolean,
    ): CreateTreeResponse {
        calls += "getTree"
        lastGetTreeRecursive = recursive
        getTreeThrows?.let { throw it }
        return CreateTreeResponse(sha = treeSha, tree = fakeTree, truncated = false)
    }

    override suspend fun createBlob(
        owner: String,
        repo: String,
        request: CreateBlobRequest,
    ): CreateBlobResponse {
        calls += "createBlob"
        blobRequests += request
        createBlobThrows?.let { throw it }
        blobCount++
        return CreateBlobResponse(sha = "blob-sha-$blobCount")
    }

    override suspend fun createTree(
        owner: String,
        repo: String,
        request: CreateTreeRequest,
    ): CreateTreeResponse {
        calls += "createTree"
        lastCreateTreeRequest = request
        createTreeThrows?.let { throw it }
        return CreateTreeResponse(sha = "new-tree-sha", tree = request.tree)
    }

    override suspend fun createCommit(
        owner: String,
        repo: String,
        request: CreateCommitRequest,
    ): CreateCommitResponse {
        calls += "createCommit"
        createCommitThrows?.let { throw it }
        return CreateCommitResponse(
            sha = "commit-sha-999",
            message = request.message,
            htmlUrl = "https://github.com/octocat/hello-world/commit/commit-sha-999",
        )
    }

    override suspend fun updateRef(
        owner: String,
        repo: String,
        ref: String,
        request: UpdateRefRequest,
        expectedSha: String,
    ): GitRef {
        calls += "updateRef"
        lastUpdateRefRef = ref
        lastUpdateRefRequest = request
        lastUpdateRefExpectedSha = expectedSha
        updateRefThrows?.let { throw it }
        return GitRef(
            ref = ref,
            obj = GitRefObject(sha = request.sha, type = "commit"),
        )
    }
}
